class P48CierreCicles():
    def __init__(self):
        self.list = ['CTJON1','CTJON3','ACE3','ACE4','ALG3','AMBIETA','ARCOS1','ARCOS2','ARCOS3'
        ,'ARRU1','ARRU2','BAHIAB','BES3','BES4','BES5','CAMGI10','CAMGI20','COL4','CTGN1','CTGN2',
        'CTGN3','CTJON2','CTN3','CTN4','CTNU','ECT2','ECT3','ESC6','ESCCC1','ESCCC2','ESCCC3',
        'MALA1','PALOS1','PALOS2','PALOS3','PBCN1','PBCN2','PGR5','PVENT1','PVENT2','SAGU1','SAGU2',
        'SAGU3','SBO3','SRI4','SRI5','SROQ1','SROQ2','STC4','TAPOWER']
